### ISSUE TITLE
Minor Corrections for About page

### ISSUE THREAD

**Issue by Morranr** [davidrea/indxd#10]
Just a few minor typos and such that I noticed on the About page.  Should be a quick fix.
- In the second paragraph, the link to Twitter labelled Myke also goes to Brad's Twitter account.  Should go to /imyke instead.
- In the first paragraph under the "Count me In" heading, it mentions 'the "Sign in / up" menu', which on the menu itself is called "Sign in / Join".  Swap one or the other for consistency.
- "Cloud-Transfer" under the credits - it lists the Noune Project where the others list the Noun Project.  An extra e on the end of Noun?

Just found this and look forward to using it, just thought I'd point these out since they should be easy to quickly change.

**Comment by davidrea** [comment]
Thank you! I will get these fixed up!
