### ISSUE TITLE
Site doesn't load; presents Error 503

### ISSUE THREAD

**Issue by SpencerDub** [davidrea/indxd#12]
When I navigate to https://indxd.ink/, the site does not load. Instead, I get this message:

>503 Service Unavailable: No healthy endpoints to handle the request. If you're the owner of this app, see this article for more information: http://bit.ly/2uCFzOo

I first noticed this yesterday, when I was trying to get to the site to export backups of my journals.

**Comment by lynng** [comment]
I’ve encountered the same issue.

**Comment by SpencerDub** [comment]
This issue appears to be resolved now.

**Comment by davidrea** [comment]
Yes, forgot to log in here and close it! The SSL cert used for the connection between the app server and the database server was expired.
