### ISSUE TITLE
Edit existing entries

### ISSUE THREAD

**Issue by QuantumTea** [davidrea/indxd#3]
I've just started indexing a notebook, and it took me a few tries to get a format I liked for the entries. It would be really useful if I could have gone back and edited the existing entries, instead of deleting them and re-entering. 

Love having the index though, really useful.

**Comment by davidrea** [comment]
Glad you like it @QuantumTea! A few folks have asked for editable topics, so I've updated Indxd to make topics editable.

**Comment by QuantumTea** [comment]
Wow, that was fast! Thank you for the feature.

**Comment by davidrea** [comment]
Sure thing, you caught me during my toddler's nap time ;)
