### ISSUE TITLE
Sign-in broken

### ISSUE THREAD

**Issue by lynng** [davidrea/indxd#9]
Sign-in is broken for Safari for OS X, Chrome, Firefox 43 and Safari for iOS. No error, the button just does nothing after entering username and password. Attempts to use Return key from password field also does nothing. I confirmed I wasn't running any ad/script/content blockers and the problem persists. Tried on multiple networks - it's not the firewall either.

**Comment by davidrea** [comment]
Confirmed here on Chrome/Linux. Will take a look tonight!

**Comment by davidrea** [comment]
@lynng Can you try logging in and leaving the browser alone for a while after clicking the button? Mine is working again but occasionally the server response is significantly delayed. I may need to add a spinner...

**Comment by lynng** [comment]
I just tried, and it did eventually authenticate successfully. Maybe 60-
90 seconds. I noticed the color of the button darkens slightly, but
given the length of the delay a more obvious visual indicator would be
an improvement. Thanks!

On Wed, Jan 6, 2016, at 04:20 PM, Dave Rea wrote:

> @lynng[1] Can you try logging in and leaving the browser alone for a
> while after clicking the button? Mine is working again but
> occasionally the server response is significantly delayed. I may need
> to add a spinner...
> 
> — Reply to this email directly or view it on GitHub[2].

Links:
1. https://github.com/lynng
2. https://github.com/davidrea/indxd/issues/9#issuecomment-169465387

**Comment by davidrea** [comment]
OK thanks for the follow-up test. I noticed some lengthy delays the other night adding new books, so there may be an issue with round-trip time on the hosting side. Right now Indxd is using the free-tier Meteor hosting, and I'm in the queue to join their new paid service.

I'll look into how to add a spinner to the login button to indicate it's in progress...

**Comment by davidrea** [comment]
Indxd is now migrated to use Galaxy and DigitalOcean for hosting, so long database connection delays should be resolved!
